%YAML 1.2
---
# This is an example config file for OS-Installer.
# Place your config under /etc/os-installer/config.yaml for it to be used.
# If a value is not defined, it's default will be used.

# Some strings can have translations by appending an underscore followed by a
# language code, e.g. "name_fr" or "description_pt_BR". These parameters have
# the _LC suffix in their description. No suffix is needed for English.

# Name of the distribution.
# Default: 'Untitled'
distribution_name: 'Arkane Linux'

# Whether the installation needs an internet connection.
# Default: yes
internet_connection_required: yes

# A URL/IP address to be used to check for an existing internet connection.
# Default: 'http://nmcheck.gnome.org/check_network_status.txt'
internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

# Skip the language selection dialog by specifing a language, e.g. 'pt_BR'
# Default: no (No fixed language, not Norwegian)
fixed_language: no

# A selection of languages the installer should present by default.
# Note: For a language to be available, it needs to be provided by the system
# and the installer needs to have a translation into that language.
# Default: ['ar', 'de', 'en', 'es', 'fr', 'ja', 'ru', 'zh']
suggested_languages:
    - 'ar'
    - 'de'
    - 'en'
    - 'es'
    - 'fr'
    - 'ja'
    - 'nl'
    - 'ru'
    - 'zh'

welcome_page:
    logo    : '/usr/share/pixmaps/archlinux-logo.png'
    text    : 'A welcoming text to inform about the installation.'
    text_de : 'Ein Begrüßungstext, um die Installation zu erklären.'
    usage   : yes

minimum_disk_size: 15

offer_disk_encryption: yes

skip_user: yes
skip_locale: yes

disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center wifi'
